### PR TITLE
feat: add Ukrainian language

### PR DESCRIPTION
**Pull request by AlexHladin**
This PR adds Ukrainian language.

### CODE REVIEW

**Comment by enrique-lozano** [comment]
Thanks a lot mate! It's the first time someone helps with another language. Just fix the little things I put it before and I will merge it.

Adding another language to the app will require some more steps, like running `dart run slang` to generate the app translations or adding the language to the language selector (in the settings) to let the user change the language. However, all of these things can go on my side once it's merged.

**Comment by AlexHladin** [comment]
> Thanks a lot mate! It's the first time someone helps with another language. Just fix the little things I put it before and I will merge it.
> 
> Adding another language to the app will require some more steps, like running `dart run slang` to generate the app translations or adding the language to the language selector (in the settings) to let the user change it. However, all of these things can go on my side once it's merged.

I'm a newbie in Flutter, it is not my primary stack. Thanks for the explanation of the required command.

**Comment by enrique-lozano** [comment]
You're welcome! I'm here for anything else

**Comment by enrique-lozano** [comment]
The translations are currently in the branch `feat/add-ukranian-lang` until #166 is resolved. They will remain there until the resolution of that issue, since the currency names fail otherwise.

I considered #166 a higher priority since we would have to migrate the database with each new language that we add, so I don't want to introduce new languages until I have that resolved.

**Pull request merged**
