### PR TITLE
fix: Initially blur currency displayer

### LINKED ISSUE #246: Short delay until currency displayer is blurred
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/enrique-lozano/Monekin/blob/main/CONTRIBUTING.md#reporting-issues).
- [X] I agree to follow the [Code of Conduct](https://github.com/enrique-lozano/Monekin/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/enrique-lozano/Monekin/issues?q=is%3Aissue) that already report this problem, without success.
- [X] I have updated the app to the last released version.

### Current Behavior

When opening the application, there is a short delay until the currency displayer is blurred.

### Expected Behavior

Currency displayer should initially be blurred to not expose sensitive information even for a slight time.

### Steps to Reproduce

Open app with private mode enabled on start.

### Additional Information

PR is prepared already

### PR DESCRIPTION
**Pull request by vincius0000**
Fixes #246

### CODE REVIEW

**Comment by enrique-lozano** [comment]
It is a good temporary solution, although in the future I think we should consider keeping the splash screen until all the settings load (and saving them in memory instead of accessing the database all the time we need the value of some setting)

**Comment by vincius0000** [comment]
> Thanks for the PR! It is a good temporary solution, although in the future I think we should consider keeping the splash screen until all the settings load (and saving them in memory instead of accessing the database all the time we need the value of some setting)

Sounds like a plan! For in-memory storage we could use Shared Preferences

And for Splash screen we simply need a widget to hold screen until all relevanr services have completed, shouldn't be difficult to implement, although I haven't looked at how spread out everything in code is. I wouldn't be surprised if some parts have to be refactored.

**Comment by vincius0000** [comment]
> Thanks for the PR! It is a good temporary solution, although in the future I think we should consider keeping the splash screen until all the settings load (and saving them in memory instead of accessing the database all the time we need the value of some setting)

Sounds like a plan! For in memory storage we could use Shared Preferences

And for Splash screen, it should be fairly easy to implement. Some parts may need refactoring, depending on how easy it is to fetch the status of different services/streams as here we need all services to complete, only then show pages other than Splash screen.

**Comment by vincius0000** [comment]
On second though, there is no need to use Shared Preferences, I've looked at it too difficulty 😄

Fetching from db once and storing in memory sounds good, can be done within the service alone.

**Comment by enrique-lozano** [comment]
> On second though, there is no need to use Shared Preferences, I've looked at it too difficult 😄
> 
> Fetching from db once and storing in memory sounds good, can be done within the service alone.

Exactly!

**Comment by enrique-lozano** [comment]
This should be fixed in #259. Have to test it a little more but seems good already

**Pull request closed without merging**
