### PR TITLE
Add Taiwanese Mandarin language

### PR DESCRIPTION
**Pull request by shinebrillant**
Add Traditional Chinese translation.

### CODE REVIEW

**Comment by enrique-lozano** [comment]
Hi! Thanks a lot for contributing! I will review and merge this PR when #166 is resolved. 

Please review the file `default_categories.json` (inside `assets/sql`), because if you don't put translations there, the category names will be in english.

**Comment by shinebrillant** [comment]
`assets/sql/default_categories.json`
The language names are arranged differently. Can they be arranged according to `/i18n`?

**Comment by enrique-lozano** [comment]
Hmm, I don't think I understand you well. To add translations to the categories you just have to add a new key with your language code where you see the `names` of the categories. In the following way:

image

I think there may be a lot of documentation missing in this regard, I will try to work on it as soon as it is more available.

**Comment by shinebrillant** [comment]
The ordering of `en` and `es` is confusing and I feel uncomfortable. Can I change it by the way?

**Comment by enrique-lozano** [comment]
Oh! I see, yes of couse you can change it! The order doesn't matter in this case, but obviously it looks better to have always the same order, so thanks a lot for pointing this out

Thanks a lot again and sorry for the inconvenience!

**Pull request merged**
