### PR TITLE
New behaviour and animation for the "New transaction" button

### PR DESCRIPTION
**Pull request by ARYPROGRAMMER**
This PR addresses the Issue discussed here #244 and attempts to close it.

- Added new behavioral functionality of floating action button
- Verified testing on real android device
- All other functionalities kept same

### CODE REVIEW

**Comment by enrique-lozano** [comment]
The animation, was not working, i already fixed it and I'm still testing. Looks good already!

Thanks a lot ❤️

**Comment by ARYPROGRAMMER** [comment]
> The animation was not working, i already fixed it and I'm still testing. Looks good already!
> 
> Thanks a lot ❤️

Thanks a lot @enrique-lozano , I might have not looked into animation part. Thanks for fixing it. Let me know further

**Comment by enrique-lozano** [comment]
I also just changed the behavior a bit, now the extended version is shown every time we scroll up and not just when we are at the top of the page (like in gmail)

**Comment by enrique-lozano** [comment]
Please @ARYPROGRAMMER, test the app now (since I made some changes) and tell me if everything works as expected. If so, I will merge the PR 🚀

**Comment by ARYPROGRAMMER** [comment]
> Please @ARYPROGRAMMER, test the app now (since I made some changes) and tell me if everything works as expected. If so, I will merge the PR 🚀

I just tested the app and this lgtm. 
You can move ahead with the PR

**Comment by ARYPROGRAMMER** [comment]
> Please @ARYPROGRAMMER, test the app now (since I made some changes) and tell me if everything works as expected. If so, I will merge the PR 🚀

Also, can we add e2e tests so that we don't have to test these functionalities manually every time

**Comment by ARYPROGRAMMER** [comment]
For now I think the optimizations done by you @enrique-lozano works fine on my device and serves the purpose

**Comment by enrique-lozano** [comment]
> > Please @ARYPROGRAMMER, test the app now (since I made some changes) and tell me if everything works as expected. If so, I will merge the PR 🚀
> 
> Also, can we add e2e tests so that we don't have to test these functionalities manually every time

That would be awesome, definitely one of the big things missing from the code is testing. There are practically 0 tests in the entire app right now, so starting to introduce some will definitely be a long task. If you want to try it out that would be great, I accept any PR on this :)

**Comment by ARYPROGRAMMER** [comment]
> > > Please @ARYPROGRAMMER, test the app now (since I made some changes) and tell me if everything works as expected. If so, I will merge the PR 🚀
> > 
> > 
> > Also, can we add e2e tests so that we don't have to test these functionalities manually every time
> 
> That would be awesome, definitely one of the big things missing from the code is testing. There are practically 0 tests in the entire app right now, so starting to introduce some will definitely be a long task. If you want to try it out that would be great, I accept any PR on this :)

Surely, I would look into this soon

**Pull request merged**
